version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-image_optimizer}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    image: image-optimizer:latest
    command: gunicorn --workers=${APP_WORKERS:-2} --bind 0.0.0.0:5000 app:app
    volumes:
      - ./images:/app/images
    ports:
      - "${APP_PORT:-5000}:5000"
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-image_optimizer}
      - STORAGE_PATH=/app/images
      - WEBP_QUALITY=${WEBP_QUALITY:-80}
      - WEBP_METHOD=${WEBP_METHOD:-4}
      - AVIF_QUALITY=${AVIF_QUALITY:-65}
      - AVIF_SPEED=${AVIF_SPEED:-6}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  worker:
    image: image-optimizer:latest
    command: python worker.py
    volumes:
      - ./images:/app/images
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-postgres}@db:5432/${POSTGRES_DB:-image_optimizer}
      - STORAGE_PATH=/app/images
      - WEBP_QUALITY=${WEBP_QUALITY:-80}
      - WEBP_METHOD=${WEBP_METHOD:-4}
      - AVIF_QUALITY=${AVIF_QUALITY:-65}
      - AVIF_SPEED=${AVIF_SPEED:-6}
      - WORKER_THREADS=${WORKER_THREADS:-2}
      - POLL_INTERVAL=${POLL_INTERVAL:-1}
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    deploy:
      replicas: ${WORKER_REPLICAS:-1}

volumes:
  postgres_data: 