name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: false
        default: 'latest'
        type: string

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Generate unique version tag
        id: generate_tag
        run: |
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          TIMESTAMP=$(date +'%Y%m%d%H%M%S')
          echo "UNIQUE_TAG=${SHORT_SHA}-${TIMESTAMP}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            tosakiup/web-image-forge:${{ github.event.inputs.tag || 'latest' }}
            tosakiup/web-image-forge:${{ steps.generate_tag.outputs.UNIQUE_TAG }}
          cache-from: type=gha
          cache-to: type=gha,mode=max